"""Add cricbuzz profile column

Revision ID: 28bc3ed59a42
Revises: 574dbaf5b980
Create Date: 2026-06-15 17:36:06.765114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28bc3ed59a42'
down_revision: Union[str, Sequence[str], None] = '574dbaf5b980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('cricbuzz_profile', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'cricbuzz_profile')
    # ### end Alembic commands ###
