"""create player and stats tables

Revision ID: 574dbaf5b980
Revises: 
Create Date: 2026-06-15 11:43:08.869508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574dbaf5b980'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('batting_style', sa.String(length=50), nullable=True),
    sa.Column('bowling_style', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('current_team', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_match_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('opposition', sa.String(length=100), nullable=False),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('balls_faced', sa.Integer(), nullable=True),
    sa.Column('wickets_taken', sa.Integer(), nullable=True),
    sa.Column('overs_bowled', sa.Float(), nullable=True),
    sa.Column('runs_conceded', sa.Integer(), nullable=True),
    sa.Column('injury_sustained', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_match_stats')
    op.drop_table('players')
    # ### end Alembic commands ###
