"""add injury profile

Revision ID: 752697f7f15c
Revises: 9064294964b6
Create Date: 2026-06-23 17:23:03.493043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752697f7f15c'
down_revision: Union[str, Sequence[str], None] = '9064294964b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('injury_profile', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'injury_profile')
    # ### end Alembic commands ###
